# Generated by Django 5.2.6 on 2026-01-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0009_comisionreferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
