# Generated by Django 5.2.6 on 2026-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0011_ruleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retiro',
            name='monto_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto final que recibirá el usuario', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retiro',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto solicitado por el usuario', max_digits=12),
        ),
    ]
