# Generated by Django 6.0 on 2026-02-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0012_retiro_comision_retiro_monto_a_pagar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tragamonedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apuesta', models.DecimalField(decimal_places=2, help_text='Monto apostado por el usuario', max_digits=12)),
                ('resultado', models.CharField(help_text='Resultado de la jugada: "GANO" o "PERDIO"', max_length=10)),
                ('ganancia', models.DecimalField(decimal_places=2, help_text='Ganancia o pérdida (negativa si pierde)', max_digits=12)),
                ('simbolos', models.CharField(help_text="Símbolos obtenidos en la jugada, ej: '🍒 🍒 🍋'", max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tragamonedas_jugadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tragamonedas',
                'verbose_name_plural': 'Tragamonedas',
                'ordering': ['-fecha'],
            },
        ),
    ]
