# Generated by Django 5.2.6 on 2026-03-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0014_perfil_publicacion_comentario_amistad_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='referencia',
        ),
    ]
