# Generated by Django 5.2.6 on 2026-03-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inverso_sa', '0015_remove_transaccion_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recarga',
            name='referencia',
        ),
    ]
